### ISSUE TITLE
App not loading

### ISSUE THREAD

**Issue by downlz** [Fherlaban/succu#1]
I tried cloning this repo and run the app in native flutter sdk as well as andriod studio.However it failed to load and could only see a top grey title bar.
Is there a way to get the app running in emulator

**Comment by israelvi** [comment]
It seems that he/she only commit the initial project or tutorial., If you look into the code, as you said, there is only a gray tittle bar. I hope she/he commit all ended project.

**Comment by downlz** [comment]
Application is in development phase and proposed UI is sketch only as of now.
